/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class DarknodePayment extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): DarknodePayment;
  address: string;
  methods: {
    ETHEREUM(): TransactionObject<string>;

    VERSION(): TransactionObject<string>;

    claimOwnership(): TransactionObject<void>;

    currentCycle(): TransactionObject<BN>;

    currentCyclePayoutPercent(): TransactionObject<BN>;

    cycleChanger(): TransactionObject<string>;

    cycleStartTime(): TransactionObject<BN>;

    darknodeRegistry(): TransactionObject<string>;

    isOwner(): TransactionObject<boolean>;

    nextCyclePayoutPercent(): TransactionObject<BN>;

    owner(): TransactionObject<string>;

    pendingTokens(arg0: number | string): TransactionObject<string>;

    previousCycle(): TransactionObject<BN>;

    previousCycleRewardShare(arg0: string): TransactionObject<BN>;

    registeredTokenIndex(arg0: string): TransactionObject<BN>;

    registeredTokens(arg0: number | string): TransactionObject<string>;

    renounceOwnership(): TransactionObject<void>;

    rewardClaimed(
      arg0: string,
      arg1: number | string
    ): TransactionObject<boolean>;

    store(): TransactionObject<string>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    unclaimedRewards(arg0: string): TransactionObject<BN>;

    updateDarknodeRegistry(_darknodeRegistry: string): TransactionObject<void>;

    withdraw(_darknode: string, _token: string): TransactionObject<void>;

    withdrawMultiple(
      _darknode: string,
      _tokens: (string)[]
    ): TransactionObject<void>;

    currentCycleRewardPool(_token: string): TransactionObject<BN>;

    darknodeBalances(
      _darknodeID: string,
      _token: string
    ): TransactionObject<BN>;

    changeCycle(): TransactionObject<BN>;

    deposit(_value: number | string, _token: string): TransactionObject<void>;

    forward(_token: string): TransactionObject<void>;

    claim(_darknode: string): TransactionObject<void>;

    registerToken(_token: string): TransactionObject<void>;

    tokenPendingRegistration(_token: string): TransactionObject<boolean>;

    deregisterToken(_token: string): TransactionObject<void>;

    updateCycleChanger(_addr: string): TransactionObject<void>;

    updatePayoutPercentage(_percent: number | string): TransactionObject<void>;

    transferStoreOwnership(_newOwner: string): TransactionObject<void>;

    claimStoreOwnership(): TransactionObject<void>;
  };
  events: {
    LogCycleChangerChanged: ContractEvent<{
      _newCycleChanger: string;
      _oldCycleChanger: string;
      0: string;
      1: string;
    }>;
    LogDarknodeClaim: ContractEvent<{
      _darknode: string;
      _cycle: BN;
      0: string;
      1: BN;
    }>;
    LogDarknodeRegistryUpdated: ContractEvent<{
      _previousDarknodeRegistry: string;
      _nextDarknodeRegistry: string;
      0: string;
      1: string;
    }>;
    LogDarknodeWithdrew: ContractEvent<{
      _payee: string;
      _value: BN;
      _token: string;
      0: string;
      1: BN;
      2: string;
    }>;
    LogPaymentReceived: ContractEvent<{
      _payer: string;
      _amount: BN;
      _token: string;
      0: string;
      1: BN;
      2: string;
    }>;
    LogPayoutPercentChanged: ContractEvent<{
      _newPercent: BN;
      _oldPercent: BN;
      0: BN;
      1: BN;
    }>;
    LogTokenDeregistered: ContractEvent<string>;
    LogTokenRegistered: ContractEvent<string>;
    OwnershipTransferred: ContractEvent<{
      previousOwner: string;
      newOwner: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
